;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 12/24/2018 5:09:39 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$EF19	F000			GOTO	_main
$0008	$	_interrupt:
$0008	$CFE9	F015			MOVFF	FSR0L, ?saveFSR0
$000C	$CFEA	F016			MOVFF	FSR0H, ?saveFSR0+1
$0010	$CFE1	F017			MOVFF	FSR1L, ?saveFSR1
$0014	$CFE2	F018			MOVFF	FSR1H, ?saveFSR1+1
;timer_interrupt_4550.c,36 :: 			void interrupt()
;timer_interrupt_4550.c,38 :: 			INTCON.T0IE=0;
$0018	$9AF2	    			BCF	INTCON, 5, 0
;timer_interrupt_4550.c,39 :: 			INTCON.T0IF=0;
$001A	$94F2	    			BCF	INTCON, 2, 0
;timer_interrupt_4550.c,40 :: 			PORTB=~PORTB;
$001C	$1E81	    			COMF	PORTB, 1, 0
;timer_interrupt_4550.c,41 :: 			INTCON.T0IE=1;
$001E	$8AF2	    			BSF	INTCON, 5, 0
;timer_interrupt_4550.c,43 :: 			}
$0020	$	L_Interrupt_end:
$0020	$C015	FFE9			MOVFF	?saveFSR0, FSR0L
$0024	$C016	FFEA			MOVFF	?saveFSR0+1, FSR0H
$0028	$C017	FFE1			MOVFF	?saveFSR1, FSR1L
$002C	$C018	FFE2			MOVFF	?saveFSR1+1, FSR1H
$0030	$0011	    			RETFIE
$0052	$	_init:
;timer_interrupt_4550.c,1 :: 			void init()
;timer_interrupt_4550.c,3 :: 			T0CON.TMR0ON=1; //tmro on
$0052	$8ED5	    			BSF	T0CON, 7, 0
;timer_interrupt_4550.c,4 :: 			T0CON.T08BIT=0; //16 bit mode
$0054	$9CD5	    			BCF	T0CON, 6, 0
;timer_interrupt_4550.c,5 :: 			T0CON.T0CS=0; //internal clocl xource
$0056	$9AD5	    			BCF	T0CON, 5, 0
;timer_interrupt_4550.c,6 :: 			T0CON.f4=1; //increase in low to high
$0058	$88D5	    			BSF	T0CON, 4, 0
;timer_interrupt_4550.c,7 :: 			T0CON.f3=1; //psa   not   assigned
$005A	$86D5	    			BSF	T0CON, 3, 0
;timer_interrupt_4550.c,8 :: 			T0CON.f2=0; //psa assigned to 2 time (psa=000)
$005C	$94D5	    			BCF	T0CON, 2, 0
;timer_interrupt_4550.c,9 :: 			T0CON.f1=0;
$005E	$92D5	    			BCF	T0CON, 1, 0
;timer_interrupt_4550.c,10 :: 			T0CON.f0=0;
$0060	$90D5	    			BCF	T0CON, 0, 0
;timer_interrupt_4550.c,12 :: 			}
$0062	$0012	    			RETURN
$0032	$	_main:
;timer_interrupt_4550.c,15 :: 			void main()
;timer_interrupt_4550.c,17 :: 			init();
$0032	$EC29	F000			CALL	_init
;timer_interrupt_4550.c,19 :: 			ADCON1=0x0f;
$0036	$0E0F	    			MOVLW	15
$0038	$6EC1	    			MOVWF	ADCON1, 0
;timer_interrupt_4550.c,20 :: 			RCON.f7=1;
$003A	$8ED0	    			BSF	RCON, 7, 0
;timer_interrupt_4550.c,21 :: 			TRISB=0;
$003C	$6A93	    			CLRF	TRISB, 0
;timer_interrupt_4550.c,22 :: 			PORTB=0;
$003E	$6A81	    			CLRF	PORTB, 0
;timer_interrupt_4550.c,23 :: 			TMR0l=200;
$0040	$0EC8	    			MOVLW	200
$0042	$6ED6	    			MOVWF	TMR0L, 0
;timer_interrupt_4550.c,24 :: 			init();
$0044	$EC29	F000			CALL	_init
;timer_interrupt_4550.c,25 :: 			INTCON=0x00;
$0048	$6AF2	    			CLRF	INTCON, 0
;timer_interrupt_4550.c,26 :: 			INTCON.T0IE=1 ;//toie
$004A	$8AF2	    			BSF	INTCON, 5, 0
;timer_interrupt_4550.c,27 :: 			INTCON.GIE=1; //gie
$004C	$8EF2	    			BSF	INTCON, 7, 0
;timer_interrupt_4550.c,29 :: 			for(;;)
$004E	$	L_main_0:
;timer_interrupt_4550.c,32 :: 			}
$004E	$	L_main_2:
$004E	$D7FF	    			BRA	L_main_0
;timer_interrupt_4550.c,34 :: 			}
$0050	$D7FF	    			BRA	$
