;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 12/30/2018 3:31:12 AM
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$EF2C	F000			GOTO	_main
$003A	$	_T1_Delay:
;timer1_counter_4550.c,8 :: 			void T1_Delay()
;timer1_counter_4550.c,11 :: 			T1CON.RD16=1;    //in one 16 bit mode
$003A	$8ECD	    			BSF	T1CON, 7, 0
;timer1_counter_4550.c,12 :: 			T1CON.T1RUN=0;   //clock comes from external
$003C	$9CCD	    			BCF	T1CON, 6, 0
;timer1_counter_4550.c,13 :: 			T1CON.T1CKPS1=0; //i/p clock ps 1
$003E	$9ACD	    			BCF	T1CON, 5, 0
;timer1_counter_4550.c,14 :: 			T1CON.T1CKPS0=0;
$0040	$98CD	    			BCF	T1CON, 4, 0
;timer1_counter_4550.c,15 :: 			T1CON.T1OSCEN=0;//osc shutoff
$0042	$96CD	    			BCF	T1CON, 3, 0
;timer1_counter_4550.c,16 :: 			T1CON.TMR1CS=0;  //rc0 ip as clk on fsc/4 edge
$0044	$92CD	    			BCF	T1CON, 1, 0
;timer1_counter_4550.c,17 :: 			T1CON.T1SYNC=0;  // sync with external clk
$0046	$94CD	    			BCF	T1CON, 2, 0
;timer1_counter_4550.c,19 :: 			PIE1.TMR1IE=1;
$0048	$809D	    			BSF	PIE1, 0, 0
;timer1_counter_4550.c,20 :: 			PIR1.TMR1IF=0;
$004A	$909E	    			BCF	PIR1, 0, 0
;timer1_counter_4550.c,21 :: 			INTCON.GIE=1;
$004C	$8EF2	    			BSF	INTCON, 7, 0
;timer1_counter_4550.c,22 :: 			TMR1H=0xf8;
$004E	$0EF8	    			MOVLW	248
$0050	$6ECF	    			MOVWF	TMR1H, 0
;timer1_counter_4550.c,23 :: 			TMR1l=0x30;
$0052	$0E30	    			MOVLW	48
$0054	$6ECE	    			MOVWF	TMR1L, 0
;timer1_counter_4550.c,24 :: 			}
$0056	$0012	    			RETURN
$0008	$	_interrupt:
$0008	$C000	F019			MOVFF	STACK_0, STSAVED_0
$000C	$CFE9	F015			MOVFF	FSR0L, ?saveFSR0
$0010	$CFEA	F016			MOVFF	FSR0H, ?saveFSR0+1
$0014	$CFE1	F017			MOVFF	FSR1L, ?saveFSR1
$0018	$CFE2	F018			MOVFF	FSR1H, ?saveFSR1+1
;timer1_counter_4550.c,51 :: 			void interrupt()
;timer1_counter_4550.c,53 :: 			PORTD=~PORTD;
$001C	$1E83	    			COMF	PORTD, 1, 0
;timer1_counter_4550.c,54 :: 			T1_Delay();
$001E	$EC1D	F000			CALL	_T1_Delay
;timer1_counter_4550.c,55 :: 			T1CON.TMR1ON=1;
$0022	$80CD	    			BSF	T1CON, 0, 0
;timer1_counter_4550.c,56 :: 			}
$0024	$	L_Interrupt_end:
$0024	$C015	FFE9			MOVFF	?saveFSR0, FSR0L
$0028	$C016	FFEA			MOVFF	?saveFSR0+1, FSR0H
$002C	$C017	FFE1			MOVFF	?saveFSR1, FSR1L
$0030	$C018	FFE2			MOVFF	?saveFSR1+1, FSR1H
$0034	$C019	F000			MOVFF	STSAVED_0, STACK_0
$0038	$0011	    			RETFIE
$0058	$	_main:
;timer1_counter_4550.c,27 :: 			void main()
;timer1_counter_4550.c,31 :: 			TRISB=0;
$0058	$6A93	    			CLRF	TRISB, 0
;timer1_counter_4550.c,32 :: 			TRISD=0;
$005A	$6A95	    			CLRF	TRISD, 0
;timer1_counter_4550.c,33 :: 			TRISC=0x03; //rc0 as input
$005C	$0E03	    			MOVLW	3
$005E	$6E94	    			MOVWF	TRISC, 0
;timer1_counter_4550.c,34 :: 			INTCON.PEIE=1;
$0060	$8CF2	    			BSF	INTCON, 6, 0
;timer1_counter_4550.c,35 :: 			T1_Delay();
$0062	$EC1D	F000			CALL	_T1_Delay
;timer1_counter_4550.c,36 :: 			T1CON.TMR1ON=1;
$0066	$80CD	    			BSF	T1CON, 0, 0
;timer1_counter_4550.c,38 :: 			while(1)
$0068	$	L_main_0:
$0068	$D7FF	    			BRA	L_main_0
;timer1_counter_4550.c,50 :: 			}
$006A	$D7FF	    			BRA	$
